// Derives src/tilemap.ts from the dungeonmode asset pack. Run: npm run gen
import { readFileSync, writeFileSync, copyFileSync, mkdirSync } from "node:fs";

const PACK = "dungeonmode";
const TILE = 8;

const seg = new Intl.Segmenter("en", { granularity: "grapheme" });
const graphemes = (s) => [...seg.segment(s)].map((x) => x.segment);

const charFile = readFileSync(`${PACK}/playscii/charsets/dungeon-mode.char`, "utf8");
const [, , dims, ...body] = charFile.split(/\r?\n/);
const [cols, rows] = dims.split(",").map((n) => parseInt(n, 10));

const sheet = body.filter((l) => l.length).map(graphemes);
if (sheet.length !== rows) throw new Error(`expected ${rows} rows, got ${sheet.length}`);

const map = {};
const dupes = [];
sheet.forEach((row, y) => {
  if (row.length !== cols) throw new Error(`row ${y}: expected ${cols} cells, got ${row.length}`);
  row.forEach((ch, x) => {
    if (ch in map) dupes.push(ch);
    map[ch] = [x * TILE, y * TILE];
  });
});

// Palette: first 24 entries are real, the rest are zero padding
const palText = readFileSync(`${PACK}/rexpaint/data/palettes/dungeon-pal.txt`, "utf8");
const palette = [...palText.matchAll(/\{\s*(\d+),\s*(\d+),\s*(\d+)\}/g)]
  .slice(0, 24)
  .map(([, r, g, b]) => "#" + [r, g, b].map((n) => (+n).toString(16).padStart(2, "0")).join(""));

const out = `// GENERATED by scripts/gen-tilemap.mjs - do not edit
export const TILE = ${TILE};

export const TILE_MAP: Record<string, [number, number]> = ${JSON.stringify(map)};

export const SHEET: string[][] = ${JSON.stringify(sheet)};

export const PALETTE: string[] = ${JSON.stringify(palette)};
`;

mkdirSync("src", { recursive: true });
mkdirSync("public", { recursive: true });
writeFileSync("src/tilemap.ts", out);
copyFileSync(`${PACK}/bitmap/dungeon-mode.png`, "public/dungeon-mode.png");

console.log(`tilemap: ${Object.keys(map).length} glyphs, palette: ${palette.length} colors`);
if (dupes.length) console.warn(`duplicate glyphs (later wins): ${dupes.join(" ")}`);
